document.writeln("<style>");
document.writeln("#mobileHeader .mobileNavList { background:#ededed;}");
document.writeln("#mobileHeader .nav_mobile a { float:none; width:100%; padding:0;}");
document.writeln("#mobileHeader .nav_mobile ul{margin-top:10px; }");
document.writeln("#mobileHeader .nav_mobile li{float: left;width: 25%;height: 36px;padding:0 10px;margin-bottom:15px;overflow: hidden;background: rgba(237,237,237,1);box-sizing:border-box;-moz-box-sizing:border-box; -webkit-box-sizing:border-box;}");
document.writeln("#mobileHeader .nav_mobile li a{display: block;line-height: 34px;text-align:center;color: #555;font-size: 16px;background: #fff;border: 1px solid #d8d8d8;-moz-border-radius: 5px;-webkit-border-radius: 5px;border-radius: 5px;}");
document.writeln("</style>");
document.writeln("<div class=\"nav_mobile\">");
document.writeln("  <ul class=\"clearfix\">");
document.writeln("    <li> <a  href=\"http://www.news.cn/\" title=\"\"> 首页 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/politics/\" title=\"\"> 时政 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/world/index.htm\" title=\"\"> 国际 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/fortune/\" title=\"\"> 财经 </a> </li>");
document.writeln("    <li> <a  href=\"http://ent.news.cn/\" title=\"\"> 娱乐 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/sports/\" title=\"\"> 体育 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/renshi/index.htm\" title=\"\"> 人事 </a> </li>");
document.writeln("    <li> <a  href=\"http://education.news.cn/\" title=\"\"> 教育 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/fashion/\" title=\"\"> 时尚 </a> </li>");
document.writeln("    <li> <a  href=\"http://sike.news.cn/\" title=\"\"> 思客 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/local/index.htm\" title=\"\"> 地方 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/legal/index.htm\" title=\"\"> 法治 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/gangao/index.htm\" title=\"\"> 港澳 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/tw/index.htm\" title=\"\"> 台湾 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/overseas/index.htm\" title=\"\"> 华人 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/auto/index.htm\" title=\"\"> 汽车 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/tech/index.htm\" title=\"\"> 科技 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/energy/index.htm\" title=\"\"> 能源 </a> </li>");
document.writeln("    <li> <a  href=\"http://forum.home.news.cn/index.jsp\" title=\"\"> 论坛 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/comments/index.htm\" title=\"\"> 网评 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/photo/index.htm\" title=\"\"> 图片 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/video/index.htm\" title=\"\"> 视频 </a> </li>");
document.writeln("    <li> <a  href=\"http://blog.home.news.cn/\" title=\"\"> 博客 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/food/index.htm\" title=\"\"> 食品 </a> </li>");
document.writeln("    <li> <a  href=\"http://travel.news.cn/\" title=\"\"> 旅游 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/health/\" title=\"\"> 健康 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/info/index.htm\" title=\"\"> 信息化 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/video/datanews/qb.htm\" title=\"\"> 数据 </a> </li>");
document.writeln("    <li> <a  href=\"http://xuan.news.cn/\" title=\"\"> 炫空间 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/gongyi/index.htm\" title=\"\"> 公益 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/yuqing/index.htm\" title=\"\"> 舆情 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/newmedia/index.htm\" title=\"\"> 传媒 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/video/dxw/index.htm\" title=\"\"> 动新闻 </a> </li>");
document.writeln("    <li> <a  href=\"http://www.news.cn/foto/index.htm\" title=\"\"> 摄影 </a> </li>");
document.writeln("    <li style=\"width: 48%;padding: 0 5px 0 10px;\"> <a href=\"http://www.news.cn/video/xinhuaradio/index.htm\" title=\"\">新华广播</a> </li>");
document.writeln("    <li style=\"width: 37%;padding: 0 5px;\"> <a href=\"http://www.news.cn/2015wlds/index.htm\" title=\"\">新华电视中文</a> </li>");
document.writeln("    <li style=\"width: 37%;padding: 0px 4px 0 6px;\"> <a href=\"http://www.news.cn/2015wlds/enindex.htm\" title=\"\">新华电视英文</a> </li>");
document.writeln("    <li> <a  href=\"http://www.xinhuanet.com/?f=pad\" title=\"\">返回PC</a></li>");
document.writeln("  </ul>");
document.writeln("</div>");